config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    after_commit do |post|
        # Get the total number of post with same name
        nameTotalPosts = Post.where("name='"+post.name+"'").count()
        # Get blog record with entered name
        blogRecord = Blog.find_by(name: post.name)
        
        # If nill, create one record
        if blogRecord == nil
            Blog.create(name: post.name, counter: nameTotalPosts)
        else
            blogRecord.counter = nameTotalPosts
            blogRecord.save
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :counter)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, class: "form-horizontal") do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class:"col-lg-2 control-label" %>
    <div class="col-lg-10">
        <%= form.text_field :name, id: :blog_name, class:"form-control", placeholder: "Name" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :counter, class:"col-lg-2 control-label" %>
    <div class="col-lg-10">
        <%= form.number_field :counter, id: :blog_counter, class:"form-control", placeholder: "Counter" %>
    </div>
  </div>

  <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= form.submit class:"btn btn-primary btn-sm" %>
      </div>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path, class:"btn btn-default btn-sm" %>
<%= link_to 'Show', @blog, class:"btn btn-primary btn-sm" %>

app/views/blogs/index.html.erb
<% if notice %>
<p id="notice">
<br>
<div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= notice %>
</div>
</p>
<% end %>

<h1>Blogs</h1>

<%= link_to 'New Blog', new_blog_path, class: "btn btn-primary btn-sm" %>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Counter</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= blog.counter %></td>
        <td><%= blog.created_at %></td>
        <td><%= blog.updated_at %></td>
        <td><%= link_to 'Show', blog, class: "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog), class: "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blogs/new.html.erb
<br><br>
<fieldset>
    <legend>New Blog</legend>
    <%= render 'form', blog: @blog %>
    <%= link_to 'Back', blogs_path, class:"btn btn-default btn-sm" %>
</fieldset>

app/views/blogs/show.html.erb
<br><br>
<% if notice %>
<p id="notice">
<div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= notice %>
</div>
</p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @blog.name %>
</p>

<p>
  <strong>Counter:</strong>
  <%= @blog.counter %>
</p>

<%= link_to 'Back', blogs_path, class:"btn btn-default btn-sm" %>
<%= link_to 'Edit', edit_blog_path(@blog), class:"btn btn-primary btn-sm" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SCS App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">Social Connect Solutions App</a>
          </div>

          <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 1px;">
            <ul class="nav navbar-nav">
              <li <% if request.original_fullpath == '/' %>class="active"<% end %>><%= link_to "Home", controller: "welcome", action: "index" %></li>
              <li <% if request.original_fullpath.scan(/blogs/i).length == 1 %>class="active"<% end %>><%= link_to 'Blogs', blogs_path %></li>
              <li <% if request.original_fullpath.scan(/posts/i).length == 1 %>class="active"<% end %>><%= link_to 'Posts', posts_path %></li>
            </ul>
          </div>
        </div>
    </nav>
    
    <div class="page-header">
        <div class="col-lg-12">
            <div class="container">
                <%= yield %>
            </div>
        </div>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, class: "form-horizontal") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class:"col-lg-2 control-label" %>
    <div class="col-lg-10">
        <%= form.text_field :name, id: :post_name, class:"form-control", placeholder: "Name" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :title, class:"col-lg-2 control-label" %>
    <div class="col-lg-10">
        <%= form.text_field :title, id: :post_title, class:"form-control", placeholder: "Title" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :body, class:"col-lg-2 control-label" %>
    <div class="col-lg-10">
        <%= form.text_area :body, id: :post_body, class:"form-control", placeholder: "Body" %>
    </div>
  </div>

  <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <!-- <%= link_to 'Back', posts_path, class:"btn btn-default btn-sm" %> -->
        <%= form.submit class:"btn btn-primary btn-sm" %>
      </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class:"btn btn-default btn-sm" %>
<%= link_to 'Show', @post, class:"btn btn-primary btn-sm" %>

app/views/posts/index.html.erb
<% if notice %>
<p id="notice">
<br>
<div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= notice %>
</div>
</p>
<% end %>

<h1>Posts</h1>

<%= link_to 'New Post', new_post_path, class: "btn btn-primary btn-sm" %>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Body</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.created_at %></td>
        <td><%= post.updated_at %></td>
        <td><%= link_to 'Show', post, class: "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary btn-sm" %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<br><br>
<fieldset>
    <legend>New Post</legend>
    <%= render 'form', post: @post %>
    <%= link_to 'Back', posts_path, class:"btn btn-default btn-sm" %>
</fieldset>

app/views/posts/show.html.erb
<br><br>
<% if notice %>
<p id="notice">
<br><br>
<div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <%= notice %>
</div>
</p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Back', posts_path, class:"btn btn-default btn-sm" %>
<%= link_to 'Edit', edit_post_path(@post), class:"btn btn-primary btn-sm" %>

app/views/welcome/index.html.erb
<h1>Create Post Summary</h1>
<%= column_chart Post.group_by_day(:created_at).count %>